id = "jetbrains-new-ui-icons"
name = "JetBrains New UI Theme"
version = "1.0.0"
schema_version = 1
authors = ["ANKDDEV"]
description = "JetBrains New UI icons theme for Zed"
repository = "https://github.com/ankddev/zed-jetbrains-newui-icons"
